---
abstract: 'Query a PostgreSQL database asynchronously'
author:
  - 'Salvador Fandino <sfandino@yahoo.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-Pg
no_index:
  directory:
    - t
    - inc
requires:
  AnyEvent: 5.34
  Method::WeakCallback: 0.01
  Pg::PQ: 0.06
version: 0.12
