--- #YAML:1.0
name:               AnyEvent-Pg
version:            0.01
abstract:           Query a PostgreSQL database asynchronously
author:
    - Salvador Fandino <sfandino@yahoo.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    AnyEvent:  5.34
    Pg::PQ:    0.04
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
